import Navbar from "@/components/shared/navbar/navbar";
import NotifyBar from "@/components/shared/notifyBar/notifyBar";
import { Hanken_Grotesk, Poppins } from "next/font/google";
import "../globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const grotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${grotesk.variable} antialiased`}>
        <NotifyBar />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
